### ISSUE TITLE
How to put faces to the  generated videos

### ISSUE THREAD

**Issue by nitinmukesh** [X-niper/UniTalker#10]
I have generated the videos but how to put faces to these?

https://github.com/user-attachments/assets/62b6e318-ff48-4d81-b25e-5f13db41b801

https://github.com/user-attachments/assets/f3dc9532-8d63-4391-9351-0c8fdc27dc6f

**Comment by X-niper** [comment]
> I have generated the videos but how to put faces to these?
> 
>  angry1_D0.mp4 
>  angry1_D1.mp4

Hi,  glad to see your results.  Could you please clarify your question? 
Do you mean how to drive real faces?  

This model drive 3D faces (meshes, blenshapes) with audio inputs, if you want to use audios to drive videos or images, you might need to seek works on 2D audio-driven tasks.

Hope this answers your question.
