### ISSUE TITLE
rendering about arkit (D6, D7)

### ISSUE THREAD

**Issue by duan348733684** [X-niper/UniTalker#12]
I used the LiveLink app to collect ARKit data for rendering.
 I took the values of the first 51 blendshapes and used the command： 

`python` -m main.render ./test_audios_ours_arkit_result/demo.npz ./test_audios_ours_arkit ./test_audios_ours_arkit_result/ for rendering,

but the result is as follows. 

https://github.com/user-attachments/assets/f6b2c0df-65cd-462e-bc0c-b7eac41b7eee

Why is this happening? 
Do the original ARKit data I collected need any preprocessing?

**Comment by X-niper** [comment]
> I used the LiveLink app to collect ARKit data for rendering. I took the values of the first 51 blendshapes and used the command：
> 
> `python` -m main.render ./test_audios_ours_arkit_result/demo.npz ./test_audios_ours_arkit ./test_audios_ours_arkit_result/ for rendering,
> 
> but the result is as follows.
> 
>  20240816-164637.mp4 
> Why is this happening? Do the original ARKit data I collected need any preprocessing?

Hi, please refer to this issue https://github.com/X-niper/UniTalker/issues/5, where we privide the meaning of the 51 blendshapes. You may need to align the orders of the blendshapes

**Comment by ggzzzzz628** [comment]
how to align blendshapes? we need 56 bs (pose+expression) @X-niper
