### ISSUE TITLE
standard retopology method

### ISSUE THREAD

**Issue by QinZhenBo** [X-niper/UniTalker#13]
The paper: 4.4 Comparison With Data Preprocessing
Specifically, for vertex-based datasets like D0 (BIWI) and D2 (Multiface), we convert the vertices into FLAME topology through standard retopology method.
Can you tell me the standard retopology method.

**Comment by X-niper** [comment]
> The paper: 4.4 Comparison With Data Preprocessing Specifically, for vertex-based datasets like D0 (BIWI) and D2 (Multiface), we convert the vertices into FLAME topology through standard retopology method. Can you tell me the standard retopology method.

We adopt nonrigid ICP for the retopology. The implementation is inhouse but you can find some open-source implementation like https://github.com/RhythmJnh/Non-rigid-ICP.  By the way, you can try some commercial software like R3DS Wrap3.

**Comment by QinZhenBo** [comment]
> > The paper: 4.4 Comparison With Data Preprocessing Specifically, for vertex-based datasets like D0 (BIWI) and D2 (Multiface), we convert the vertices into FLAME topology through standard retopology method. Can you tell me the standard retopology method.
> 
> We adopt nonrigid ICP for the retopology. The implementation is inhouse but you can find some open-source implementation like https://github.com/RhythmJnh/Non-rigid-ICP. By the way, you can try some commercial software like R3DS Wrap3.

The original non rigid ICP algorithm did not perform well. Have you made any improvements?

**Comment by X-niper** [comment]
> > > The paper: 4.4 Comparison With Data Preprocessing Specifically, for vertex-based datasets like D0 (BIWI) and D2 (Multiface), we convert the vertices into FLAME topology through standard retopology method. Can you tell me the standard retopology method.
> > 
> > 
> > We adopt nonrigid ICP for the retopology. The implementation is inhouse but you can find some open-source implementation like https://github.com/RhythmJnh/Non-rigid-ICP. By the way, you can try some commercial software like R3DS Wrap3.
> 
> The original non rigid ICP algorithm did not perform well. Have you made any improvements?

Yes, the implementation is not exactly the same with the original one. The implementations of non-rigid ICP differ a lot.  We pay many efforts on the implementation and it's not trivial, including the keypoints selection, and hyperparemeters settings.
