### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by hdjang** [X-niper/UniTalker#15]
Hi
Thanks for sharing great work!!

I have a simple question regarding training 
- How can I increas the 'batch size' to higher than '1' ?
- what batch size did you use for training in the paper?

Best regards,
HDJ

**Comment by X-niper** [comment]
> Hi Thanks for sharing great work!!
> 
> I have a simple question regarding training
> 
> * How can I increas the 'batch size' to higher than '1' ?
> * what batch size did you use for training in the paper?
> 
> Best regards, HDJ

We use batchsize =1, and keep the original audio length and face motion length. If you want to increase batchsize per gpu > 1, please modify dataset class, pad the data and add padding_mask.
