### ISSUE TITLE
where is "flame.pkl"?

### ISSUE THREAD

**Issue by anddyhzw** [X-niper/UniTalker#17]
I have downloaded the code. When I ran the command "python -m main.demo --config config/unitalker.yaml test_out_path ./test_results/demo.npz", an error happend, just like below:
    with open(model_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/binary_resources/flame.pkl'

**Comment by X-niper** [comment]
> I have downloaded the code. When I ran the command "python -m main.demo --config config/unitalker.yaml test_out_path ./test_results/demo.npz", an error happend, just like below: with open(model_path, 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: 'resources/binary_resources/flame.pkl'

Hi, anddyhzw

[FLAME2020](https://flame.is.tue.mpg.de/download.php): Please download FLAME 2020 and move generic_model.pkl into resources/binary_resources/flame.pkl.

We have updated README to help future researchers.
