### ISSUE TITLE
pca.npz file

### ISSUE THREAD

**Issue by hdjang** [X-niper/UniTalker#18]
Hi
Thanks for sharing your great work!

I wonder what does "pca.npz" file under "D0_BIWI", "D1_vocaset", "D2_meshtalk" folder include ?
Does it include pca annotation of all data in each dataset?
If so, how can I use it to get vertex annotation from them?

**Comment by X-niper** [comment]
> Hi Thanks for sharing your great work!
> 
> I wonder what does "pca.npz" file under "D0_BIWI", "D1_vocaset", "D2_meshtalk" folder include ? Does it include pca annotation of all data in each dataset? If so, how can I use it to get vertex annotation from them?

Hi, the pca components are got from the training set. To the the vertex annotation, you need to download them from the original link following README.md

**Comment by hdjang** [comment]
Ah ha I got it. Thanks for the detailed reply !! :)
