### ISSUE TITLE
Can I get the blendshape rather than vertex data?

### ISSUE THREAD

**Issue by MOr1s2** [X-niper/UniTalker#23]
Your work is excellent! 
And I have a question, the output of the model here is the vertex data corresponding to different formats, but I only want to get the corresponding blendshape data, is there a way to get it?

**Comment by MOr1s2** [comment]
I figured out how to export ARKIT blendshapes, but when I import the output blendshapes into the engine, I find that the rendered video is quite different. Is there something wrong here?

**Comment by X-niper** [comment]
> I figured out how to export ARKIT blendshapes, but when I import the output blendshapes into the engine, I find that the rendered video is quite different. Is there something wrong here?

Hi, please refer to this issue https://github.com/X-niper/UniTalker/issues/5, where we privide the meaning of the 51 blendshapes. You may need to align the orders of the blendshapes

**Comment by MOr1s2** [comment]
> > I figured out how to export ARKIT blendshapes, but when I import the output blendshapes into the engine, I find that the rendered video is quite different. Is there something wrong here?
> 
> Hi, please refer to this issue #5, where we privide the meaning of the 51 blendshapes. You may need to align the orders of the blendshapes

Thank you! I have solved it.

**Comment by JosephKKim** [comment]
Hello! @MOr1s2, I also want to get blendshapes instead of vertices how did you managed to get blendshapes?
