### ISSUE TITLE
可以分享处理后的D0-D4数据集么

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [X-niper/UniTalker#24]
非常棒的工作，我目前尝试基于你们的方法在metahuman animators上做支持，实验上微调的效果不完美，可以分享处理后的D0-D4数据集么，我想要这几个数据集一起重新训练；我发现几个数据集已经失效，并且其中的预处理工作量非常大......

**Comment by X-niper** [comment]
> 非常棒的工作，我目前尝试基于你们的方法在metahuman animators上做支持，实验上微调的效果不完美，可以分享处理后的D0-D4数据集么，我想要这几个数据集一起重新训练；我发现几个数据集已经失效，并且其中的预处理工作量非常大......

Hi, 这里主要设计一些版权问题，不过 D1 -Vocaset 的下载和处理相对容易， D0下载已经失效，D3-D4的下载相对容易https://github.com/psyai-net/EmoTalk_release ， 可以先下载这些来一起训练哈

**Comment by ZHANG-SHI-CHANG** [comment]
> > 非常棒的工作，我目前尝试基于你们的方法在metahuman animators上做支持，实验上微调的效果不完美，可以分享处理后的D0-D4数据集么，我想要这几个数据集一起重新训练；我发现几个数据集已经失效，并且其中的预处理工作量非常大......
> 
> Hi, 这里主要设计一些版权问题，不过 D1 -Vocaset 的下载和处理相对容易， D0下载已经失效，D3-D4的下载相对容易https://github.com/psyai-net/EmoTalk_release ， 可以先下载这些来一起训练哈

非常感谢！
