### ISSUE TITLE
关于训练代码中的疑问1

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [X-niper/UniTalker#25]
非常棒的项目！最近在根据业务需求重新训练该项目，在data_item中发现一个问题，当音频超过20s时，会默认做截断处理，但是D3/D4/D7数据集中存在不少几分钟的数据，这是不是一种浪费？如果不在data_item中做截断，在dataloader中做随机的20s长度数据截取是不是更好一点呢
![image](https://github.com/user-attachments/assets/a00af790-a714-475e-a89d-fd5d608c5713)

**Comment by X-niper** [comment]
> 非常棒的项目！最近在根据业务需求重新训练该项目，在data_item中发现一个问题，当音频超过20s时，会默认做截断处理，但是D3/D4/D7数据集中存在不少几分钟的数据，这是不是一种浪费？如果不在data_item中做截断，在dataloader中做随机的20s长度数据截取是不是更好一点呢 ![image](https://private-user-images.githubusercontent.com/30692249/379756707-a00af790-a714-475e-a89d-fd5d608c5713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzMwMDEsIm5iZiI6MTcyOTgzMjcwMSwicGF0aCI6Ii8zMDY5MjI0OS8zNzk3NTY3MDctYTAwYWY3OTAtYTcxNC00NzVlLWE4OWQtZmQ1ZDYwOGM1NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA1MDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTkyMDU1YjhiMmZkNGUwYWFiNWFhOGNkZWFjN2Y3Yjc2MWUzZjQ5NDgwYjA5ZTBmZGYyNTRmMzYxNWQ1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZtGOTK703tmemnLLWw8UmNKXZo8HY8Iky30dEUp8qY)

嗨，这个是我们代码中一块写死的逻辑哈，是为了防止训练时爆显存的哈，可以把这块逻辑删掉，或者把这个最长时常写入到config文件中，设置一个很大的值。

除此之外，您的方法也是有效的，这样子既可以防止显存爆，也可以用到数据的不同段，确实更全面地利用到数据。

**Comment by ZHANG-SHI-CHANG** [comment]
> > 非常棒的项目！最近在根据业务需求重新训练该项目，在data_item中发现一个问题，当音频超过20s时，会默认做截断处理，但是D3/D4/D7数据集中存在不少几分钟的数据，这是不是一种浪费？如果不在data_item中做截断，在dataloader中做随机的20s长度数据截取是不是更好一点呢 ![image](https://private-user-images.githubusercontent.com/30692249/379756707-a00af790-a714-475e-a89d-fd5d608c5713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzMwMDEsIm5iZiI6MTcyOTgzMjcwMSwicGF0aCI6Ii8zMDY5MjI0OS8zNzk3NTY3MDctYTAwYWY3OTAtYTcxNC00NzVlLWE4OWQtZmQ1ZDYwOGM1NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA1MDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTkyMDU1YjhiMmZkNGUwYWFiNWFhOGNkZWFjN2Y3Yjc2MWUzZjQ5NDgwYjA5ZTBmZGYyNTRmMzYxNWQ1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VZtGOTK703tmemnLLWw8UmNKXZo8HY8Iky30dEUp8qY)
> 
> 嗨，这个是我们代码中一块写死的逻辑哈，是为了防止训练时爆显存的哈，可以把这块逻辑删掉，或者把这个最长时常写入到config文件中，设置一个很大的值。
> 
> 除此之外，您的方法也是有效的，这样子既可以防止显存爆，也可以用到数据的不同段，确实更全面地利用到数据。

感谢回复，如此便好
