### ISSUE TITLE
Can I get the flame expression rather than vertex data?

### ISSUE THREAD

**Issue by wzr1201** [X-niper/UniTalker#26]
Hi, great work! I have a question, how can I extract the flame expression data from the vertex data? 

from the rendered video, can I assume that shape and pose params of flame are invariant?

**Comment by X-niper** [comment]
> Hi, great work! I have a question, how can I extract the flame expression data from the vertex data?
> 
> from the rendered video, can I assume that shape and pose params of flame are invariant?

Hi, for D1 (vocaset) dataset, we can't get directly get these parameters. We need a post optimization to get them. For D5 (faceforencis) dataset, we can get the parameters but the qualitiy is not as good as the D1 output head. 

The shape params can be assumed invariant, the expression and pose params are variant.

**Comment by wzr1201** [comment]
thanks very mush for your reply， I got it
