### ISSUE TITLE
No such file or directory: './unitalker_data_release/BIWI/id_template.npy'

### ISSUE THREAD

**Issue by jimydavis** [X-niper/UniTalker#3]
Hi is this file supposed to be inside one of the downloads?

No such file or directory: './unitalker_data_release/BIWI/id_template.npy'

Thank you

**Comment by gary109** [comment]
me too

**Comment by X-niper** [comment]
> Thank you

Hi, we released the three datasets we collected in this work. Previously released datasets are not included. 

To get id_template for BIWI or Vocaset, you can download the datasets following the link in README, and then store their template.pkl file into id_template.npy by throw the key and save just the vertices.

Note that, the id order shold be consistent with train.json. Please download our dataset to see the data structure.

**Comment by X-niper** [comment]
> Hi is this file supposed to be inside one of the downloads?
> 
> No such file or directory: './unitalker_data_release/BIWI/id_template.npy'
> 
> Thank you

Hi, we just uploaded the id_template.zip to google cloud  https://drive.google.com/file/d/1Xr3mHyIBf5Hdy8l16JOlnv0QMNFLp268/view?usp=sharing . 

We will update README

**Comment by X-niper** [comment]
> Thank you very much! The original BIWI dataset is no longer available btw. Do you know if it moved to a different platform or something?
> 
> Thank you again.

I just found that too.  I don't know how to get the original data in this case. We have the prepared data, but we can't distribute it due to the license issue.

If your target is to train the model, we recomend to use our released data first. Besides, you can you use meshtalk and vocaset, and 3DETF datasets. They have good data quality.
