### ISSUE TITLE
Can I get the arkit blendshape rather than vertex data?

### ISSUE THREAD

**Issue by yufenglv** [X-niper/UniTalker#30]
Your work is excellent!
And I have a question, the output of the model here is the vertex data corresponding to different formats, but I only want to get the corresponding blendshape data, is there a way to get it?
Same question like this: https://github.com/X-niper/UniTalker/issues/23

**Comment by X-niper** [comment]
> Your work is excellent! And I have a question, the output of the model here is the vertex data corresponding to different formats, but I only want to get the corresponding blendshape data, is there a way to get it? Same question like this: #23

Hi，

please comment out this line to get the original output instead of the vertices.
https://github.com/X-niper/UniTalker/blob/main/main/demo.py#L181

**Comment by yufenglv** [comment]
> > Your work is excellent! And I have a question, the output of the model here is the vertex data corresponding to different formats, but I only want to get the corresponding blendshape data, is there a way to get it? Same question like this: #23
> 
> Hi，
> 
> please comment out this line to get the original output instead of the vertices. https://github.com/X-niper/UniTalker/blob/main/main/demo.py#L181

Thanks!
