### ISSUE TITLE
avatar's mouth is often open

### ISSUE THREAD

**Issue by toreal** [X-niper/UniTalker#36]
Thank you for your excellent work! During my tests, I noticed that the avatar's mouth is often open, even when there is no sound. Is this related to the initial state of the template, or is it because the mouth doesn't return to a closed state when not speaking? If it should return to a closed state when silent, what would be the best way to handle this?

https://github.com/user-attachments/assets/78314f38-143f-46bb-bb5c-b7f3946b0032

**Comment by X-niper** [comment]
> Thank you for your excellent work! During my tests, I noticed that the avatar's mouth is often open, even when there is no sound. Is this related to the initial state of the template, or is it because the mouth doesn't return to a closed state when not speaking? If it should return to a closed state when silent, what would be the best way to handle this?
> 
>  angry2_D0.mp4

Hi, this is related with the template. 
<img width="310" alt="image" src="https://github.com/user-attachments/assets/6af11ddc-e301-4169-a872-ec73454d08aa" />
You can use a template with closed mouth regarding this issue.

**Comment by Alpe6825** [comment]
@X-niper is there any reason why all templates of the demo have open mouths? I noticed that in your [video](https://youtu.be/oUUh67ECzig?feature=shared&t=103) the mouth always close after speaking.

**Comment by ggzzzzz628** [comment]
@Alpe6825 Have you solved the problem? I had the same problem, I couldn't find the right template

**Comment by toreal** [comment]
I found that the results of D5 inference are greatly influenced by the template. Since the template represents an average value, it seems to increase the likelihood of the mouth being open. I'm not quite sure why the template is included. When I tried running it without the template, most of the results showed a closed mouth. Would multiplying a certain value help in this case? @X-niper, what are your thoughts? I've attached the results without the template for reference.

https://github.com/user-attachments/assets/75edcee8-70dd-46fd-8d6b-949ef5eca3f3

**Comment by ggzzzzz628** [comment]
Where did you get this template? Can you send me the file? Thank you very much! @toreal  @X-niper

**Comment by toreal** [comment]
https://github.com/X-niper/UniTalker/blob/main/models/unitalker.py

```
 if (not self.use_pca) or (annot_type not in self.pca_layer_dict):
            out_motion = self.out_head_dict[annot_type](decoder_out)
            out_motion = out_motion 
            out_pca, gt_pca = None, None
        else:
            out_pca = self.out_head_dict[annot_type](decoder_out)
            out_motion = self.pca_layer_dict[annot_type].decode(
                out_pca, self.pca_dim)
            out_motion = out_motion 
```

**Comment by ggzzzzz628** [comment]
> https://github.com/X-niper/UniTalker/blob/main/models/unitalker.py
> 
> ```
>  if (not self.use_pca) or (annot_type not in self.pca_layer_dict):
>             out_motion = self.out_head_dict[annot_type](decoder_out)
>             out_motion = out_motion 
>             out_pca, gt_pca = None, None
>         else:
>             out_pca = self.out_head_dict[annot_type](decoder_out)
>             out_motion = self.pca_layer_dict[annot_type].decode(
>                 out_pca, self.pca_dim)
>             out_motion = out_motion 
> ```

How does this code work?
My template does open by default, it looks like your template is , is it re-exported a new template?

**Comment by toreal** [comment]
For the D0, D1, and D2 data, the template represents the average position of the vertices. However, for D5, it represents the expression parameters. Is it equally appropriate to directly add the template in this case? I’m not sure—perhaps the author has more experience with this. Since the final comparison is based on vertex positions, the out_motion could represent the displacement difference. But since the parameters are derived from PCA, is it appropriate to apply the same concept of displacement difference? I’m uncertain.

I tried not adding the template, and in most cases, the mouth remains closed. Does a larger parameter value cause the mouth to open, while a smaller value causes it to close? Perhaps it’s worth investigating whether the mouth's opening and closing are more closely related to the value range of the expression parameters. That’s why I’d like to ask for the author’s opinion on this.

**Comment by ggzzzzz628** [comment]
So how do you get a template where the default mouth is closed ,thks! @toreal

**Comment by toreal** [comment]
I did not use the template, just as mentioned in the previous post.

**Comment by rohit7044** [comment]
@toreal  I tried using your hack on D0 but it gives me an overflow error. Can you share what you have done to handle overflow? Or this code is only for D5?
`Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase.`
The result mesh was also a bit messed up. Any leads will be great thanks!

**Comment by toreal** [comment]
From what I recall, this issue didn’t occur. I didn’t retrain; I just tried running inference.

**Comment by rohit7044** [comment]
Is this hack only for D5?
Also, Do you think there's a way to convert BIWI to FLAME parameters?
