### ISSUE TITLE
Blendshape Attributes for D6, D7

### ISSUE THREAD

**Issue by kraj011** [X-niper/UniTalker#5]
Hi!
UniTalker is awesome, congratulations!
I wanted to ask about datasets D6 and D7.
They seem to reference the open source ARKit blenshape weights (e.g. as is found [here](https://arkit-face-blendshapes.com/)), but they have a shape of 51 instead of the typical 52.
If these are indeed the same, I was wondering if you could shed some light on:
- Which blend shape attribute was removed?
- What is the ordering of the 51 blendshapes? Is it the same as [here](https://github.com/elijah-atkins/ARKitBlendshapeHelper)?

Thank you so much and congrats again!

**Comment by kraj011** [comment]
Oops! Ok Found the answer to my first question in section 3.2 of the paper:

> Our Speech(D6) and Song(D7) Datasets. Our facial capture system utilizes ARKit with a depth camera on the iPhone 13 Pro to extract 51 blendshape
weights, excluding TongueOut, at a frame rate of 60 fps.

**Comment by X-niper** [comment]
> Oops! Ok Found the answer to my first question in section 3.2 of the paper:
> 
> > Our Speech(D6) and Song(D7) Datasets. Our facial capture system utilizes ARKit with a depth camera on the iPhone 13 Pro to extract 51 blendshape
> > weights, excluding TongueOut, at a frame rate of 60 fps.

Hi, for the second question. The key list is 
[
    'EyeBlinkLeft', 'EyeBlinkRight', 'EyeSquintLeft', 'EyeSquintRight',
    'EyeLookDownLeft', 'EyeLookDownRight', 'EyeLookInLeft', 'EyeLookInRight',
    'EyeWideLeft', 'EyeWideRight', 'EyeLookOutLeft', 'EyeLookOutRight',
    'EyeLookUpLeft', 'EyeLookUpRight', 'BrowDownLeft', 'BrowDownRight',
    'BrowInnerUp', 'BrowOuterUpLeft', 'BrowOuterUpRight', 'JawOpen',
    'MouthClose', 'JawLeft', 'JawRight', 'JawForward', 'MouthUpperUpLeft',
    'MouthUpperUpRight', 'MouthLowerDownLeft', 'MouthLowerDownRight',
    'MouthRollUpper', 'MouthRollLower', 'MouthSmileLeft', 'MouthSmileRight',
    'MouthDimpleLeft', 'MouthDimpleRight', 'MouthStretchLeft',
    'MouthStretchRight', 'MouthFrownLeft', 'MouthFrownRight', 'MouthPressLeft',
    'MouthPressRight', 'MouthPucker', 'MouthFunnel', 'MouthLeft', 'MouthRight',
    'MouthShrugLower', 'MouthShrugUpper', 'NoseSneerLeft', 'NoseSneerRight',
    'CheekPuff', 'CheekSquintLeft', 'CheekSquintRight'
]
