### ISSUE TITLE
No such file or directory: 'resources/binary_resources/flame.pkl'

### ISSUE THREAD

**Issue by duan348733684** [X-niper/UniTalker#6]
Greak work!

No such file or directory: 'resources/binary_resources/flame.pkl'

**Comment by X-niper** [comment]
> Greak work!
> 
> No such file or directory: 'resources/binary_resources/flame.pkl'

Hi, due to the license issue, we can't upload it to this repo, but it's accessible here https://voca.is.tue.mpg.de/index.html. We use FLAME2020.
