### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by hdjang** [X-niper/UniTalker#8]
Hi 
Thanks for sharing your great work!!

I have a simple question regarding demo

I got below error when I run demo code. What flame.pkl file should I have to prepare?
FileNotFoundError: [Errno 2] No such file or directory: 'resources/binary_resources/flame.pkl'

Best regards

**Comment by X-niper** [comment]
> Hi Thanks for sharing your great work!!
> 
> I have a simple question regarding demo
> 
> I got below error when I run demo code. What flame.pkl file should I have to prepare? FileNotFoundError: [Errno 2] No such file or directory: 'resources/binary_resources/flame.pkl'
> 
> Best regards

Hi, due to the license issue, we can't upload it to this repo, but it's accessible here https://voca.is.tue.mpg.de/index.html. We use FLAME2020.

**Comment by wzr0108** [comment]
I downloaded FLAME2020.zip from https://flame.is.tue.mpg.de/download.php. After extracting it, there are three files: female_model.pkl, generic_model.pkl, and male_model.pkl. The file flame.pkl is not included

**Comment by X-niper** [comment]
> I downloaded FLAME2020.zip from https://flame.is.tue.mpg.de/download.php. After extracting it, there are three files: female_model.pkl, generic_model.pkl, and male_model.pkl. The file flame.pkl is not included

Hi, we use generic_model.pkl. You could rename this file or edit the path in our code. 

Hope it helps.
